### ISSUE TITLE
Unable to connect to backend

### ISSUE THREAD

**Issue by DGovender** [littleweeb/Desktop#19]
Hi.

I wanted to try using your application however I am running linux and tested it on 2 systems (Manjaro i3 18.0.4 and Ubuntu 18.04) and I got the error in the application that it is unable to connect to the backend. Is there something that needs to be installed on the linux systems so that AspNetCore works as it should or am I missing something?

Kind regards

**Comment by EldinZenderink** [comment]
This is on the discord server, try this first: 
![image](https://user-images.githubusercontent.com/12187560/55673022-90468e00-58a2-11e9-9a35-d200db9e6572.png)

Normal ubuntu comes with the dependencies for dotnet core.. but you could try, for troubleshooting try this: https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/runtime-2.2.3

**Comment by DGovender** [comment]
Thank you, I got this working. I think it was because I was using the university network where there are a lot of restrictions.
